# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: DownloadSecureFile@1
  name: jksfile
  inputs:
    secureFile: 'keystore.jks'
  displayName: 'Download keystore.jks'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main') )

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: true

- task: AndroidSigning@3
  inputs:
    apkFiles: 'app/build/outputs/apk/release/app-release-unsigned.apk'
    apksignerKeystoreFile: 'keystore.jks'
    apksignerKeystorePassword: '$(KEY_STORE_PASSWORD)'
    apksignerKeystoreAlias: 'calculator'
    apksignerKeyPassword: '$(KEY_STORE_PASSWORD)'
    apksignerFile: 'app/build/outputs/apk/release/app-release.apk'
    zipalign: false

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts